name: build

on: [push, pull_request]

jobs:
  build:
#    runs-on: ubuntu-16.04
    strategy:
      matrix:
        go: [ '1.15' ]
    name: Go ${{ matrix.go }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - run: go build./angle
